const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.jumpthru,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.System.Cnds.Compare
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Sprite: 0},
	{TiledBackground4: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{player_walk: 0},
	{d9f3827d08ab468a891d69d815974c: 0},
	{TiledBackground5: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Keyboard: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Spike: 0},
	{Text: 0},
	{Text2: 0},
	{Anchor: 0},
	{Stopwatch: 0},
	{Text3: 0},
	{Text4: 0},
	{DeathCounter: 0},
	{Jumpthru: 0},
	{TiledBackground6: 0},
	{Audio: 0},
	{counterdeath: 0},
	{TiledBackground7: 0},
	{Sprite10: 0},
	{dist: 0},
	{highscore: 0},
	{LocalStorage: 0},
	{seconds: 0},
	{minutes: 0},
	{metres: 0},
	{hours: 0},
	{deaths: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	player_walk: class extends self.ISpriteInstance {},
	d9f3827d08ab468a891d69d815974c: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Stopwatch: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	DeathCounter: class extends self.ITextInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	counterdeath: class extends self.ITextInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	dist: class extends self.ITextInstance {},
	highscore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {}
}